# Generated by Django 5.0.1 on 2024-01-31 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('closePrice', models.FloatField(blank=True, default=0)),
                ('openPrice', models.FloatField(blank=True, default=0)),
                ('prevClosePrice', models.FloatField(blank=True, default=0)),
                ('change', models.FloatField(blank=True, default=0)),
                ('state', models.CharField(default='stay', max_length=10)),
                ('timeStamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['symbol', 'name'],
                'indexes': [models.Index(fields=['symbol', 'name'], name='livePrice_t_symbol_95fdd4_idx')],
            },
        ),
    ]
